server:
  port: 8183
spring:
  datasource:
    url: jdbc:h2:file:./db
    username: u
    password: 1
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: tester404tester@gmail.com
    password: olxrsaxtbcgmcygd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
nbu:
  currency:
    url: https://nbu.uz/uz/exchange-rates/json/
email:
  subject: Confirmation email
  sender: tester404tester@gmail.com
  activation:
    text-prefix: <a href="http://localhost:8183/api/v1/auth/confirmation-email/%s">Click</a>